### ISSUE TITLE
Implement event filtering

### ISSUE THREAD

**Issue by n4r1b** [n4r1b/ferrisetw#6]
**Info**
ETW allows filters to be defined for a Provider in a session. [MSDN - Defining Filters](https://docs.microsoft.com/en-us/windows/win32/wes/defining-filters). 
KrabsETW already provides a mechanism to do filtering either by events_id or by using more complicated predicates
- https://github.com/microsoft/krabsetw/tree/master/krabs/krabs/filtering

**TODO**
* [ ] Research best way to introduce filters into Ferris
* [x] Implement a basic filtering based on events_id
* [ ] Research and implement a filtering based on more complex predicates

**Comment by daladim** [comment]
We're now able to filter by Event ID.

Predicates are left TODO
